package com.glutilities.test;
import org.lwjgl.glfw.GLFW;
import org.lwjgl.opengl.GL11;

import com.glutilities.gui.GLWindow;
import com.glutilities.gui.Renderer;
import com.glutilities.gui.Scene;
import com.glutilities.gui.SceneProjection;
import com.glutilities.gui.scene.OrthographicProjection;
import com.glutilities.text.FontManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) {
    	GLFW.glfwInit();
    	
    	SceneProjection ortho = new OrthographicProjection(0, 1, 1, 0, -1, 1);
    	SceneProjection perspective = null;
    	
    	Scene scene = new Scene(ortho, perspective, false);
    	
    	GLWindow window = new GLWindow(800, 600, "Testing", 0, scene);
    	
    	FontManager fm = new FontManager();
    	fm.load("Arial", "arial");
    	
    	window.addRenderer(new Renderer(Renderer.ORTHOGRAPHIC_SCENE) {

			@Override
			public void render() {
				Main.render(fm, window);
			}
    		
    	});
    	
    	window.init();
    	window.makeContextCurrent();
    	window.loop();
    }
    
    private static void render(FontManager fm, GLWindow window) {
    	GL11.glColor3d(1, 1, 1);
    	GL11.glBegin(GL11.GL_QUADS);
    	GL11.glVertex2d(0.25, 0.25);
    	GL11.glVertex2d(0.25, 0.75);
    	GL11.glVertex2d(0.75, 0.75);
    	GL11.glVertex2d(0.75, 0.25);
    	GL11.glEnd();
    	FontManager.drawString(fm.get("arial"), "test", 0.5, 0.5, 0.01, window.getWindowAspect(), 0.1);
    }
}
